services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: ms-sql-server
    restart: always
    ports:
      - "1433:1433/tcp"
    env_file:
      - .env
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    networks:
      - fpt-swp
  ms-sql-init:
    image: mcr.microsoft.com/mssql-tools
    container_name: ms-sql-init
    restart: no
    volumes:
      - ./entrypoint.sh:/usr/src/entrypoint.sh
    entrypoint: ["/bin/bash", "/usr/src/entrypoint.sh"]
    env_file:
      - .env
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - ms-sql-server
    networks:
      - fpt-swp
  koi-fish-be:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: koi-fish-be
    restart: unless-stopped
    ports:
      - "8080:8080/tcp"
    volumes:
      - ./images:/app/images
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - DB_HOST=ms-sql-server
    env_file:
      - .env
    depends_on:
      - ms-sql-init
    networks:
      - fpt-swp

networks:
  fpt-swp:
    driver: bridge
